<template>
  <dialog id="update_modal" class="modal">
    <div class="modal-box">
      <h3 class="text-lg font-bold">Attention</h3>
      <p class="py-4">
        Updating the POG files will overwrite all files on your keyboard generated by POG (e.g.
        kb.py, code.py, customkeys.py, etc.)
      </p>
      <p class="py-4">Be sure to backup your code if you still need any of it.</p>
      <div class="flex justify-between">
        <div class="btn" @click="closeModal">Abort</div>
        <div class="btn btn-error" @click="updatePOG">Update POG files</div>
      </div>
    </div>
    <form method="dialog" class="modal-backdrop">
      <button>close</button>
    </form>
  </dialog>
  <div class="mt-4 p-4 text-left">
    <p>
      <a href="https://kmkfw.io/" target="_blank" class="link">KMK</a> is a capable firmware for
      keyboards using the Rp2040.
    </p>
    <p>
      Before you proceed make sure you installed
      <a class="link" href="https://circuitpython.org/downloads" target="_blank">CircuitPython</a>
      on your controller
    </p>
    <p>
      Info: This does not work when the controller is only connected via the serial port (and not as
      mounted usb drive)
    </p>
    <br />
    <p v-if="!keyboardStore.firmwareInstalled">
      By clicking the button below, you can install KMK automatically to the following drive:
      <span class="font-mono">{{ keyboardStore.path }}</span>
    </p>
    <div class="holder">
      <div class="flex justify-center">
        <div v-if="keyboardStore.firmwareInstalled" class="stats mt-8 shadow-xl">
          <div class="stat text-left">
            <div class="stat-figure text-primary">
              <i class="mdi mdi-check text-3xl"></i>
            </div>
            <div class="stat-title">Firmware Installed</div>
            <div class="stat-value text-primary">KMK</div>
            <!--        <div class="stat-desc">modified on</div>-->
          </div>
        </div>
      </div>
      <div
        v-if="['', 'done'].includes(kmkInstallState)"
        class="mt-8 flex flex-col items-center justify-center"
      >
        <div class="mt-8 grid grid-cols-2 justify-center gap-4">
          <button class="btn btn-primary" @click="updateKMK">
            {{ keyboardStore.firmwareInstalled ? 'update' : 'install' }} KMK
          </button>
          <button class="btn btn-primary" @click="openModal">update Firmware</button>
        </div>
        <button class="btn btn-primary mt-8" @click="updateKMK">install KMK</button>
      </div>
      <div v-if="initialSetup" class="mt-8 flex justify-center">
        <button
          v-if="keyboardStore.firmwareInstalled"
          class="btn btn-primary mt-4 block"
          @click="$emit('next')"
        >
          Next
        </button>
        <button class="btn mt-4 block" @click="$emit('next')">I installed KMK manually</button>
      </div>

      <div
        v-if="['downloading', 'copying', 'unpacking'].includes(kmkInstallState)"
        class="mt-4 flex flex-col items-center justify-center"
      >
        <p class="m-4 mt-8">{{ kmkInstallState || '' }}</p>
        <progress class="progress progress-primary w-56" :value="progress" max="100"></progress>
        <span v-if="progress !== 0"> {{ isNaN(progress) ? 'Done' : progress }}% </span>
      </div>
    </div>
  </div>
</template>
<script setup lang="ts">
import { ref } from 'vue'
import { keyboardStore } from '../store'
import dayjs from 'dayjs'

const progress = ref(0)
const kmkInstallState = ref('')

defineProps<{ initialSetup: boolean }>()
defineEmits(['next'])
const startTime = ref(dayjs())
const endTime = ref(dayjs())

const updateKMK = async () => {
  await window.api.updateFirmware()
  kmkInstallState.value = 'downloading'
  startTime.value = dayjs()
}

const updatePOG = async () => {
  window.api.saveConfiguration(
    JSON.stringify({ pogConfig: keyboardStore.serialize(), writeFirmware: true })
  )
  closeModal()
}

const openModal = () => {
  ;(document.getElementById('update_modal') as HTMLDialogElement).showModal()
}

const closeModal = () => {
  ;(document.getElementById('update_modal') as HTMLDialogElement).close()
}

window.api.onUpdateFirmwareInstallProgress(
  (_event: Event, value: { state: string; progress: number }) => {
    console.log('kmk progress', value)
    // don't go back from done
    if (kmkInstallState.value !== 'done') {
      kmkInstallState.value = value.state
      console.log('progress', value.progress)
      progress.value = Math.round(value.progress)
      if (value.state === 'done') {
        keyboardStore.firmwareInstalled = true
        endTime.value = dayjs()
        console.log(startTime.value, endTime.value)
      }
    }
  }
)
</script>
