import * as fs from 'fs-extra'
import { currentKeyboard } from './store'
// save code.py based on pog.json

export const saveConfiguration = (data: string) => {
  const { pogConfig, writeFirmware } = JSON.parse(data)
  // write pog.json config
  // write pog.json
  fs.writeFile(currentKeyboard.path + '/pog.json', JSON.stringify(pogConfig, null, 4), () => {
    console.log('pog File written successfully\n')
  })
  if (writeFirmware) {
    console.log('should also write firmware files')
    handleKeymapSave(pogConfig)
  }
}

export const handleKeymapSave = (pogConfig) => {
  console.log('saving keymap', pogConfig)
  // const codeblockraw = fs.readFileSync(`${keyboardPath}/code.py`, {encoding:'utf8', flag:'r'})
  // console.log(codeblockraw)
  // const codeblock = codeblockraw.match(/# CodeBlock([\S\s]*)# \/CodeBlock/gm)[1]
  // console.log(codeblock)
  // create basic keymap file
  // grab old codeblocks
  let pythonImports = ''
  let kmkAddons = ''
  let codeblock = ''
  //layers
  if (true) {
    pythonImports += '\nfrom kmk.modules.layers import Layers\n'
    kmkAddons += '\nkeyboard.modules.append(Layers())\n'
  }

  //media keys
  if (true) {
    pythonImports += '\nfrom kmk.extensions.media_keys import MediaKeys\n'
    kmkAddons += '\nkeyboard.extensions.append(MediaKeys())\n'
  }
  // testing encoder enable
  if (pogConfig.encoders && pogConfig.encoders.length !== 0) {
    pythonImports +=
      '\nfrom kmk.modules.layers import Layers\n' +
      'from kmk.modules.encoder import EncoderHandler\n'
    kmkAddons +=
      '\nlayers = Layers()\n' +
      'encoder_handler = EncoderHandler()\n' +
      'keyboard.modules = [layers, encoder_handler]\n'

    let encoderPins = ''
    pogConfig.encoders.forEach((encoder) => {
      encoderPins += `(board.GP${encoder.pad_a}, board.GP${encoder.pad_b}, None,),`
    })

    let encoderKeymap = ''
    // keymap: [layer[encoder[keys]]
    pogConfig.encoderKeymap.forEach((layer) => {
      encoderKeymap += '('
      layer.forEach((encoder) => {
        encoderKeymap += `(${encoder.join(',')},),`
      })
      encoderKeymap += '),\n'
    })

    codeblock +=
      '# Encoder\n' +
      'encoder_handler.pins = (\n' +
      encoderPins +
      '\n' +
      ')\n' +
      'encoder_handler.map = [ \n' +
      encoderKeymap + // layers
      ']\n'
  }
  const mainConfig = `# Main Keyboard Configuration
print("Starting ${pogConfig.name || 'Keyboard'}")

import board
import storage

from kb import KMKKeyboard
from kmk.modules.tapdance import TapDance

from storage import getmount
from kmk.modules.split import Split, SplitType, SplitSide
${pythonImports}

keyboard = KMKKeyboard()
${kmkAddons}

tapdance = TapDance()
tapdance.tap_time = 200
keyboard.modules.append(tapdance)

# Keymap
from keymap import keymap
keyboard.keymap = keymap

${codeblock}

if __name__ == '__main__':
    keyboard.go()
`
  // write kb.py for basic config
  let pinSetup = ``
  if (pogConfig.wiringMethod === 'matrix') {
    pinSetup = `
    col_pins = (${pogConfig.colPins.map((a) => 'board.GP' + a).join(', ')})
    row_pins = (${pogConfig.rowPins.map((a) => 'board.GP' + a).join(', ')})
    diode_orientation = DiodeOrientation.${pogConfig.diodeDirection}
`
  } else {
    pinSetup = `
    def __init__(self):
        # create and register the scanner
        self.matrix = KeysScanner(
            # require argument:
            pins=[${pogConfig.directPins.map((a) => 'board.GP' + a).join(', ')}],
            # optional arguments with defaults:
            value_when_pressed=False,
            pull=True,
            interval=0.02,  # Debounce time in floating point seconds
            max_events=64
        )
    `
  }

  const kbConfig = `# KB base config
import board
from kmk.kmk_keyboard import KMKKeyboard as _KMKKeyboard
from kmk.scanners import DiodeOrientation
from kmk.scanners import intify_coordinate as ic
from kmk.scanners.keypad import KeysScanner

class KMKKeyboard(_KMKKeyboard):
    ${pinSetup}
 `

  const keymap = `# Keymap Autogenerated by Pog do not edit
from kmk.keys import KC
from kmk.handlers.sequences import send_string
import customkeys

keymap = [
    ${pogConfig.keymap.map((layer) => '[' + layer.join(', ') + ']').join(', ')}
]
`
  fs.writeFile(currentKeyboard.path + '/kb.py', kbConfig, () => {
    console.log('kb File written successfully\n')
  })
  fs.writeFile(currentKeyboard.path + '/code.py', mainConfig, () => {
    console.log('Firmware File written successfully\n')
  })
  fs.writeFile(currentKeyboard.path + '/keymap.py', keymap, () => {
    console.log('keymap File written successfully\n')
  })
  if (!fs.existsSync(currentKeyboard.path + '/customkeys.py')) {
    const defaultCustomKeys = `# These are yous custom keycodes do any needed imports at the top
# then you can reference them in your keymap with for example customkeys.MyKey

from kmk.keys import KC

MyKey = KC.X
`
    fs.writeFile(currentKeyboard.path + '/customkeys.py', defaultCustomKeys, () => {
      console.log('customkeys File written successfully\n')
    })
  }
}
